#QUESTAO 1

SELECT
  SUM(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS Pagamentos,
  COUNT(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) As Qtde,
  PRODUCTS.PRODUCTNAME
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
  INNER JOIN CUSTOMERS ON (ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER)
  INNER JOIN PAYMENTS ON (CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER)
WHERE
  YEAR(PAYMENTDATE) = 2003  
GROUP BY
  PRODUCTS.PRODUCTNAME
ORDER BY
  SUM(AMOUNT) desc
LIMIT 20;

#QUESTAO 2

SELECT
   MONTH(PAYMENTDATE) AS MES,
   FORMAT(AVG(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach),2) AS MEDIA,
   MAX(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS MAXIMO,
   MIN(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS MINIMO
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
  INNER JOIN CUSTOMERS ON (ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER)
  INNER JOIN PAYMENTS ON (CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER)
  INNER JOIN EMPLOYEES ON (CUSTOMERS.SALESREPEMPLOYEENUMBER = EMPLOYEES.employeeNumber)
  INNER JOIN OFFICES ON (EMPLOYEES.OFFICECODE = OFFICES.OFFICECODE)
WHERE
    YEAR(PAYMENTDATE) = 2004
AND OFFICES.CITY = 'Paris'
GROUP BY
  MONTH(PAYMENTDATE)
ORDER BY
  MES;
 
 
#QUESTAO 3

SELECT
  PRODUCTS.PRODUCTNAME AS PRODUTO,
  SUM(ORDERDETAILS.quantityOrdered) AS QTDE
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
WHERE
  MONTH(requiredDate) BETWEEN 9 AND 12
GROUP BY
  PRODUCTS.PRODUCTNAME;
 
#QUESTAO 4

SELECT
  COUNT(CUSTOMERS.CUSTOMERNUMBER) AS QTDE,
  OFFICES.CITY AS ESCRITORIO
FROM
   CUSTOMERS
   INNER JOIN EMPLOYEES ON (CUSTOMERS.SALESREPEMPLOYEENUMBER = EMPLOYEES.EMPLOYEENUMBER)
   INNER JOIN OFFICES ON (EMPLOYEES.OFFICECODE =OFFICES.OFFICECODE)
GROUP BY
   OFFICES.CITY
ORDER BY
   QTDE DESC;  
   

#QUESTAO 5
 SELECT
  SUM(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS Pagamentos,
  COUNT(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) As Qtde,
  PRODUCTS.PRODUCTNAME
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
  INNER JOIN CUSTOMERS ON (ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER)
  INNER JOIN PAYMENTS ON (CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER)
WHERE
    YEAR(PAYMENTDATE) = 2004  
AND MONTH(PAYMENTDATE) BETWEEN 1 AND 6  
GROUP BY
  PRODUCTS.PRODUCTNAME
ORDER BY
  SUM(AMOUNT) desc
LIMIT 15;

#QUESTAO 6

 SELECT
   MONTH(PAYMENTDATE) AS MES,
   FORMAT(AVG(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach),2) AS MEDIA,
   MAX(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS MAXIMO,
   MIN(ORDERDETAILS.quantityOrdered * ORDERDETAILS.priceEach) AS MINIMO
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
  INNER JOIN CUSTOMERS ON (ORDERS.CUSTOMERNUMBER = CUSTOMERS.CUSTOMERNUMBER)
  INNER JOIN PAYMENTS ON (CUSTOMERS.CUSTOMERNUMBER = PAYMENTS.CUSTOMERNUMBER)
  INNER JOIN EMPLOYEES ON (CUSTOMERS.SALESREPEMPLOYEENUMBER = EMPLOYEES.employeeNumber)
  INNER JOIN OFFICES ON (EMPLOYEES.OFFICECODE = OFFICES.OFFICECODE)
WHERE
    YEAR(PAYMENTDATE) = 2003
AND OFFICES.CITY = 'Tokyo'
GROUP BY
  MONTH(PAYMENTDATE)
ORDER BY
  MES;



#QUESTAO 7

SELECT
  PRODUCTS.PRODUCTNAME AS PRODUTO,
  SUM(ORDERDETAILS.quantityOrdered) AS QTDE
FROM
  PRODUCTS
  INNER JOIN ORDERDETAILS ON (PRODUCTS.productCode = ORDERDETAILS.productCode)
  INNER JOIN ORDERS ON (ORDERDETAILS.ORDERNUMBER = ORDERS.ORDERNUMBER)
WHERE
   MONTH(requiredDate) BETWEEN 9 AND 12
GROUP BY
  PRODUCTS.PRODUCTNAME
ORDER BY
  QTDE;
