CREATE DATABASE AULA_PROCEDURE;
USE AULA_PROCEDURE;

DROP TABLE FOOD;
CREATE TABLE FOOD(
ID INT UNSIGNED NOT NULL auto_increment PRIMARY KEY,
TIPO_COMIDA VARCHAR(150)
)ENGINE = INNODB;

DROP PROCEDURE REPETICAO_COM_WHILE;
-- WHILE
DELIMITER $$


CREATE PROCEDURE REPETICAO_COM_WHILE()
BEGIN
   DECLARE V_MAX INT UNSIGNED DEFAULT 100;
   DECLARE V_COUNTER INT unsigned default 0;
   
-- ESTRUTURA DE REPETIÇÃO 
WHILE V_COUNTER < V_MAX DO
	INSERT INTO FOOD (TIPO_COMIDA) VALUES (concat('COMIDA',V_COUNTER));
	SET V_COUNTER = V_COUNTER + 1;
END WHILE;

END $$

$$ DELIMITER ; 

SELECT * FROM FOOD;

CALL REPETICAO_COM_WHILE


-- UTILIZAÇÃO DO REPEAT
DELIMITER $$
DROP PROCEDURE REPETICAO_COM_REPEAT;
CREATE PROCEDURE REPETICAO_COM_REPEAT()
BEGIN
	DECLARE X INT; -- DECLARAÇÃO DE VARIAVEL DE CONTROLE
    DECLARE STR VARCHAR(200); -- DECLARAÇÃO DE VARIAVEL MANIPULADA
    
    SET X =10; -- INICIALIZAÇÃO DE VARIAVEL
    SET STR = '';
    REPEAT -- INICIO DA ESTRUTURA DE VARIAVEL 
    SET STR = concat(STR, X, ','); -- atualização da variável manipulada
    set x = x - 1; -- atualização da variavel de controle 
    until x <= 0 -- validação da repetição 
END REPEAT;

SELECT STR; -- APRESENTAÇÃO DO RESULTADO 

END 
$$ DELIMITER ; 

CALL REPETICAO_COM_REPEAT;

