USE CLASSICMODELS;
  
  DELIMITER $$
CREATE PROCEDURE CLIENTES_ATENDIDOS(IN ESCRITORIO VARCHAR(40), IN ANO INT) 
BEGIN
	SELECT 
		CUSTOMERS.CUSTOMERNAME
	FROM 
		PAYMENTS
		INNER JOIN CUSTOMERS USING (CUSTOMERNUMBER)
		INNER JOIN EMPLOYEES ON (SALESREPEMPLOYEENUMBER = EMPLOYEENUMBER)
		INNER JOIN OFFICES USING (OFFICECODE)
	WHERE 
		year(paymentdate) = ANO AND offices.city = ESCRITORIO;
END
$$ DELIMITER ;
CALL CLIENTES_ATENDIDOS("Paris", 2004);

DROP PROCEDURE CLIENTES_ATENDIDOS
